version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3333:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /home/milirbaba/docker/adguardhome/workdir:/opt/adguardhome/work
      - /home/milirbaba/docker/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped